import type { LexemeEntry, PartOfSpeech } from "../domain/types";
import { splitMeanings } from "./meanings";

/**
 * The rest of the top thousand.
 *
 * The dictionary already held about half of the thousand most common words,
 * scattered across the frequency file, the pronouns, the question words and the
 * thematic topics. These are the other half: everything the frequency order
 * names that had no entry anywhere.
 *
 * Written as dictionary entries, including the verbs. A verb here gets a
 * meaning card — "parecer — казаться" — and not a conjugation deck, because
 * conjugation is a separate and much heavier commitment: it needs the
 * irregularities checked one form at a time, and a wrong ending taught
 * confidently is worse than an ending not taught at all. Promoting any of them
 * to a full verb entry later costs nothing and loses no progress, since the
 * word keeps its own card either way.
 *
 * Nouns carry their gender so the list can show them with an article, which is
 * the only reliable way to learn it.
 */

/** Compact authoring form: [spanish, russian, part of speech, gender?]. */
type Row = [es: string, ru: string, pos: PartOfSpeech, gender?: "m" | "f"];

const ROWS: Row[] = [
  // --- 1-100 -------------------------------------------------------------
  ["eso", "это (то, о чём речь)", "pronoun"],
  ["sí", "да", "adverb"],
  ["haber", "иметься, быть", "verb"],
  ["hola", "привет", "other"],
  ["ti", "тебе, тебя", "pronoun"],
  ["mí", "мне, меня", "pronoun"],
  ["parecer", "казаться", "verb"],
  ["donde", "где, куда (в утверждении)", "conjunction"],
  ["hecho", "факт, дело", "noun", "m"],
  ["tal", "такой", "adjective"],

  // --- 101-200 -----------------------------------------------------------
  ["fuera", "вне, за пределами", "adverb"],
  ["tipo", "тип, парень", "noun", "m"],
  ["acuerdo", "согласие, договор", "noun", "m"],
  ["gustar", "нравиться", "verb"],
  ["menos", "меньше", "adverb"],
  ["mal", "плохо", "adverb"],
  ["importar", "иметь значение", "verb"],
  ["aún", "всё ещё, даже", "adverb"],
  ["quizá", "возможно", "adverb"],
  ["muerto", "мёртвый", "adjective"],
  ["realmente", "действительно", "adverb"],
  ["cariño", "дорогой (обращение)", "noun", "m"],
  ["lado", "сторона", "noun", "m"],
  ["alguno", "какой-то, некоторый", "pronoun"],
  ["cuidado", "осторожность", "noun", "m"],
  ["auto", "авто", "noun", "m"],
  ["adiós", "до свидания", "other"],
  ["cualquier", "любой", "adjective"],
  ["loco", "сумасшедший", "adjective"],
  ["guerra", "война", "noun", "f"],
  ["persona", "человек, личность", "noun", "f"],
  ["capitán", "капитан", "noun", "m"],
  ["adelante", "вперёд", "adverb"],
  ["listo", "готовый, смышлёный", "adjective"],
  ["junto", "рядом, вместе", "adverb"],
  ["único", "единственный", "adjective"],
  ["significar", "значить", "verb"],
  ["morir", "умирать", "verb"],
  ["ninguno", "ни один", "pronoun"],
  ["atrás", "назад, сзади", "adverb"],
  ["señora", "сеньора, госпожа", "noun", "f"],
  ["suficiente", "достаточный", "adjective"],
  ["siquiera", "хотя бы", "adverb"],
  ["suponer", "предполагать", "verb"],
  ["justo", "справедливый, как раз", "adjective"],
  ["matar", "убивать", "verb"],
  ["vuelta", "поворот, возвращение", "noun", "f"],
  ["realidad", "реальность", "noun", "f"],
  ["pregunta", "вопрос", "noun", "f"],
  ["oportunidad", "удобный случай, шанс", "noun", "f"],
  ["paso", "шаг", "noun", "m"],
  ["vivo", "живой", "adjective"],
  ["mayor", "старший, больший", "adjective"],
  ["medio", "середина, половина", "noun", "m"],
  ["arma", "оружие", "noun", "f"],
  ["dólar", "доллар", "noun", "m"],
  ["final", "финал, окончание", "noun", "m"],
  ["lista", "список", "noun", "f"],
  ["exactamente", "точно", "adverb"],
  ["seguridad", "безопасность", "noun", "f"],
  ["acá", "сюда, здесь", "adverb"],
  ["tampoco", "тоже нет", "adverb"],
  ["paz", "покой, мир (не война)", "noun", "f"],
  ["recuerdo", "воспоминание", "noun", "m"],
  ["par", "пара (штук)", "noun", "m"],
  ["pueblo", "посёлок, народ", "noun", "m"],
  ["caballero", "кавалер, джентльмен", "noun", "m"],
  ["plan", "план", "noun", "m"],
  ["correcto", "правильный", "adjective"],
  ["control", "контроль", "noun", "m"],
  ["callar", "молчать", "verb"],
  ["trato", "сделка, обращение", "noun", "m"],
  ["rey", "король", "noun", "m"],
  ["muchacho", "парень", "noun", "m"],
  ["jamás", "никогда (ни разу)", "adverb"],
  ["acerca", "насчёт, о", "preposition"],
  ["falta", "нехватка, ошибка", "noun", "f"],
  ["presidente", "президент", "noun", "m"],
  ["gusto", "вкус, удовольствие", "noun", "m"],
  ["general", "общий, генерал", "adjective"],
  ["nave", "судно, космический корабль", "noun", "f"],
  ["orden", "порядок, приказ", "noun", "f"],
  ["increíble", "невероятный", "adjective"],
  ["especial", "особенный", "adjective"],
  ["perfecto", "идеальный", "adjective"],
  ["odio", "ненависть", "noun", "m"],
  ["agente", "агент", "noun", "m"],
  ["detrás", "сзади, позади", "adverb"],
  ["real", "настоящий, королевский", "adjective"],
  ["frente", "лоб, перёд", "noun", "m"],
  ["millón", "миллион", "numeral"],
  ["asesino", "убийца", "noun", "m"],
  ["sueño", "сон, мечта", "noun", "m"],
  ["probablemente", "вероятно", "adverb"],
  ["resto", "остаток", "noun", "m"],
  ["lamentar", "сожалеть", "verb"],
  ["encima", "сверху, поверх", "adverb"],
  ["información", "информация", "noun", "f"],
  ["secreto", "секрет", "noun", "m"],
  ["incluso", "даже", "adverb"],
  ["profesor", "преподаватель", "noun", "m"],
  ["habitación", "комната (в доме, в отеле)", "noun", "f"],
  ["daño", "вред, ущерб", "noun", "m"],
  ["noticia", "новость", "noun", "f"],
  ["duro", "твёрдый, тяжёлый", "adjective"],
  ["prueba", "проба, доказательство", "noun", "f"],
  ["tonto", "глупый", "adjective"],
  ["campo", "поле, деревня", "noun", "m"],

  // --- 401-600 -----------------------------------------------------------
  ["asunto", "дело, вопрос", "noun", "m"],
  ["derecho", "право, прямой", "noun", "m"],
  ["placer", "удовольствие", "noun", "m"],
  ["ejército", "армия", "noun", "m"],
  ["futuro", "будущее", "noun", "m"],
  ["llevar", "нести, везти, носить", "verb"],
  ["compañía", "компания", "noun", "f"],
  ["sitio", "местечко, точка", "noun", "m"],
  ["puesto", "должность", "noun", "m"],
  ["atención", "внимание", "noun", "f"],
  ["error", "ошибка", "noun", "m"],
  ["raro", "странный, редкий", "adjective"],
  ["mente", "ум, разум", "noun", "f"],
  ["sistema", "система", "noun", "m"],
  ["ello", "это (оно, книжное)", "pronoun"],
  ["negocio", "бизнес, сделка", "noun", "m"],
  ["sonar", "звучать", "verb"],
  ["ocurrir", "происходить", "verb"],
  ["oficial", "офицер, официальный", "noun", "m"],
  ["aire", "воздух", "noun", "m"],
  ["regresar", "возвращаться", "verb"],
  ["señorita", "сеньорита, девушка", "noun", "f"],
  ["traje", "костюм", "noun", "m"],
  ["modo", "образ действия, режим", "noun", "m"],
  ["llamada", "звонок", "noun", "f"],
  ["pena", "жалость, наказание", "noun", "f"],
  ["foto", "фотография", "noun", "f"],
  ["accidente", "авария, несчастный случай", "noun", "m"],
  ["imposible", "невозможный", "adjective"],
  ["línea", "линия", "noun", "f"],
  ["barco", "корабль, лодка", "noun", "m"],
  ["normal", "нормальный", "adjective"],
  ["tras", "за, после", "preposition"],
  ["lindo", "милый, славный", "adjective"],
  ["funcionar", "работать, функционировать", "verb"],
  ["programa", "программа", "noun", "m"],
  ["centro", "центр", "noun", "m"],
  ["situación", "ситуация", "noun", "f"],
  ["encantar", "очень нравиться", "verb"],
  ["marido", "муж", "noun", "m"],
  ["personal", "личный, персонал", "adjective"],
  ["hambre", "голод", "noun", "f"],
  ["ataque", "атака, приступ", "noun", "m"],
  ["conseguir", "добиваться, доставать", "verb"],
  ["derecha", "правая сторона", "noun", "f"],
  ["izquierda", "левая сторона", "noun", "f"],
  ["próximo", "ближайший, будущий", "adjective"],
  ["pobre", "бедный", "adjective"],
  ["respuesta", "ответ", "noun", "f"],
  ["vista", "зрение, вид из окна", "noun", "f"],
  ["salvo", "кроме", "preposition"],
  ["señal", "знак, сигнал", "noun", "f"],
  ["nena", "малышка", "noun", "f"],
  ["servicio", "услуга, сервис", "noun", "m"],
  ["edad", "возраст", "noun", "f"],
  ["hermoso", "красивый", "adjective"],
  ["honor", "честь", "noun", "m"],
  ["simplemente", "просто", "adverb"],
  ["humano", "человеческий, человек", "adjective"],
  ["sexo", "пол (мужской, женский), секс", "noun", "m"],
  ["peligro", "опасность", "noun", "m"],
  ["siguiente", "следующий по порядку", "adjective"],
  ["misión", "миссия, задание", "noun", "f"],
  ["silencio", "тишина", "noun", "m"],
  ["regreso", "возвращение", "noun", "m"],
  ["media", "половина часа", "noun", "f"],
  ["oro", "золото", "noun", "m"],
  ["enseguida", "сейчас же", "adverb"],
  ["norte", "север", "noun", "m"],
  ["jurar", "клясться", "verb"],
  ["interesante", "интересный", "adjective"],
  ["cumpleaños", "день рождения", "noun", "m"],
  ["abogado", "адвокат, юрист", "noun", "m"],
  ["alrededor", "вокруг", "adverb"],
  ["cerebro", "мозг", "noun", "m"],
  ["santo", "святой", "adjective"],
  ["necesario", "необходимый", "adjective"],
  ["edificio", "здание", "noun", "m"],
  ["ley", "закон", "noun", "f"],
  ["verdadero", "истинный, настоящий", "adjective"],
  ["pelea", "драка, ссора", "noun", "f"],
  ["terrible", "ужасный", "adjective"],
  ["calma", "спокойствие", "noun", "f"],
  ["gobierno", "правительство", "noun", "m"],
  ["sargento", "сержант", "noun", "m"],
  ["destino", "судьба, назначение", "noun", "m"],
  ["través", "через, сквозь", "preposition"],
  ["regalo", "подарок", "noun", "m"],
  ["cualquiera", "кто угодно", "pronoun"],
  ["excelente", "отличный", "adjective"],
  ["deseo", "желание", "noun", "m"],
  ["alma", "душа", "noun", "f"],
  ["espada", "меч", "noun", "f"],
  ["maravilloso", "чудесный", "adjective"],
  ["peligroso", "опасный", "adjective"],
  ["dirección", "направление, адрес", "noun", "f"],
  ["libertad", "свобода", "noun", "f"],
  ["sorpresa", "сюрприз, неожиданность", "noun", "f"],
  ["club", "клуб", "noun", "m"],
  ["luna", "луна", "noun", "f"],
  ["salvar", "спасать", "verb"],
  ["carta", "письмо, карта", "noun", "f"],
  ["teniente", "лейтенант", "noun", "m"],
  ["ambos", "оба", "pronoun"],
  ["decisión", "решение", "noun", "f"],
  ["enemigo", "враг", "noun", "m"],
  ["dulce", "сладкий", "adjective"],
  ["divertir", "развлекать", "verb"],
  ["puro", "чистый (без примеси)", "adjective"],
  ["asiento", "сиденье, место", "noun", "m"],
  ["vuelo", "полёт, рейс", "noun", "m"],
  ["ante", "перед", "preposition"],
  ["bienvenido", "добро пожаловать", "adjective"],
  ["contacto", "контакт", "noun", "m"],
  ["posición", "положение, позиция", "noun", "f"],
  ["planeta", "планета", "noun", "m"],
  ["coronel", "полковник", "noun", "m"],
  ["base", "база, основа", "noun", "f"],
  ["suelo", "земля (под ногами)", "noun", "m"],
  ["pelear", "драться, ссориться", "verb"],
  ["pistola", "пистолет", "noun", "f"],
  ["comandante", "командир", "noun", "m"],
  ["sur", "юг", "noun", "m"],
  ["rato", "недолгое время", "noun", "m"],
  ["espacio", "пространство, космос", "noun", "m"],
  ["asesinato", "убийство", "noun", "m"],
  ["prisa", "спешка", "noun", "f"],
  ["cámara", "камера", "noun", "f"],
  ["broma", "шутка", "noun", "f"],
  ["despertar", "будить, просыпаться", "verb"],
  ["locura", "безумие", "noun", "f"],
  ["horrible", "жуткий", "adjective"],
  ["enfermo", "больной", "adjective"],
  ["cárcel", "тюрьма", "noun", "f"],
  ["isla", "остров", "noun", "f"],
  ["salida", "выход", "noun", "f"],
  ["doler", "болеть", "verb"],
  ["crimen", "преступление", "noun", "m"],

  // --- 601-800 -----------------------------------------------------------
  ["causa", "причина", "noun", "f"],
  ["bar", "бар", "noun", "m"],
  ["río", "река", "noun", "m"],
  ["relación", "отношение, связь", "noun", "f"],
  ["droga", "наркотик", "noun", "f"],
  ["ojalá", "хоть бы, дай бог", "other"],
  ["radio", "радио", "noun", "f"],
  ["excepto", "за исключением", "preposition"],
  ["conocido", "знакомый, известный", "adjective"],
  ["investigación", "расследование, исследование", "noun", "f"],
  ["batalla", "битва", "noun", "f"],
  ["regla", "правило, линейка", "noun", "f"],
  ["cargo", "обвинение, пост", "noun", "m"],
  ["hogar", "домашний очаг, родной дом", "noun", "m"],
  ["respeto", "уважение", "noun", "m"],
  ["corte", "суд, разрез", "noun", "f"],
  ["paciente", "пациент, терпеливый", "noun", "m"],
  ["encuentro", "встреча", "noun", "m"],
  ["energía", "энергия", "noun", "f"],
  ["baile", "танец", "noun", "m"],
  ["caliente", "горячий", "adjective"],
  ["rayo", "луч, молния", "noun", "m"],
  ["simple", "простой", "adjective"],
  ["zona", "зона, район", "noun", "f"],
  ["guardia", "охранник, караул", "noun", "f"],
  ["canción", "песня", "noun", "f"],
  ["soldado", "солдат", "noun", "m"],
  ["caballo", "лошадь", "noun", "m"],
  ["interesar", "интересовать", "verb"],
  ["volar", "летать", "verb"],
  ["principio", "начало, принцип", "noun", "m"],
  ["finalmente", "наконец", "adverb"],
  ["debajo", "под, внизу", "adverb"],
  ["bosque", "лес", "noun", "m"],
  ["ocupado", "занятый", "adjective"],
  ["acaso", "разве, случайно", "adverb"],
  ["equivocado", "ошибочный, неправый", "adjective"],
  ["obra", "произведение, стройка", "noun", "f"],
  ["consejo", "совет", "noun", "m"],
  ["público", "публика, публичный", "noun", "m"],
  ["animal", "животное", "noun", "m"],
  ["apostar", "спорить, ставить", "verb"],
  ["prisión", "заключение, тюрьма", "noun", "f"],
  ["fantástico", "фантастический", "adjective"],
  ["duda", "сомнение", "noun", "f"],
  ["unido", "объединённый", "adjective"],
  ["princesa", "принцесса", "noun", "f"],
  ["miles", "тысячи", "numeral"],
  ["bomba", "бомба, насос", "noun", "f"],
  ["apenas", "едва", "adverb"],
  ["papi", "папочка", "noun", "m"],
  ["mantener", "поддерживать, содержать", "verb"],
  ["rico", "богатый, вкусный", "adjective"],
  ["acción", "действие", "noun", "f"],
  ["mando", "командование, пульт", "noun", "m"],
  ["memoria", "память", "noun", "f"],
  ["robot", "робот", "noun", "m"],
  ["montón", "куча", "noun", "m"],
  ["máquina", "механизм, станок", "noun", "f"],
  ["trago", "глоток, рюмка", "noun", "m"],
  ["mayoría", "большинство", "noun", "f"],
  ["reina", "королева", "noun", "f"],
  ["inglés", "английский", "adjective"],
  ["estrella", "звезда", "noun", "f"],
  ["valor", "ценность, смелость", "noun", "m"],
  ["delante", "впереди", "adverb"],
  ["código", "код", "noun", "m"],
  ["héroe", "герой", "noun", "m"],
  ["fe", "вера", "noun", "f"],
  ["capaz", "способный", "adjective"],
  ["velocidad", "скорость", "noun", "f"],
  ["partido", "матч, партия", "noun", "m"],
  ["opinión", "мнение", "noun", "f"],
  ["golpe", "удар", "noun", "m"],
  ["ganas", "охота, настрой", "noun", "f"],
  ["ejemplo", "пример", "noun", "m"],
  ["propósito", "намерение, замысел", "noun", "m"],
  ["anillo", "кольцо", "noun", "m"],
  ["estilo", "стиль", "noun", "m"],
  ["pista", "след, подсказка, дорожка", "noun", "f"],
  ["escapar", "убегать, спасаться", "verb"],
  ["espíritu", "дух", "noun", "m"],
  ["molestar", "мешать, беспокоить", "verb"],
  ["nota", "записка, оценка", "noun", "f"],
  ["diferencia", "разница", "noun", "f"],
  ["servir", "служить, подавать", "verb"],
  ["doble", "двойной", "adjective"],
  ["agradable", "приятный", "adjective"],
  ["embargo", "однако, тем не менее", "conjunction"],
  ["emergencia", "чрезвычайная ситуация", "noun", "f"],
  ["cuello", "шея, воротник", "noun", "m"],
  ["boda", "свадьба", "noun", "f"],
  ["informe", "отчёт, доклад", "noun", "m"],
  ["experiencia", "опыт", "noun", "f"],
  ["mentira", "ложь", "noun", "f"],
  ["director", "директор, режиссёр", "noun", "m"],
  ["exacto", "точный", "adjective"],
  ["defensa", "защита", "noun", "f"],
  ["confiar", "доверять", "verb"],
  ["color", "цвет", "noun", "m"],
  ["probar", "пробовать, доказывать", "verb"],
  ["príncipe", "принц", "noun", "m"],
  ["vacaciones", "отпуск, каникулы", "noun", "f"],
  ["fondo", "дно, фон", "noun", "m"],
  ["opción", "вариант, выбор", "noun", "f"],
  ["operación", "операция", "noun", "f"],
  ["principal", "главный", "adjective"],
  ["respecto", "касательно, в отношении", "noun", "m"],
  ["especie", "вид (биологический), разновидность", "noun", "f"],
  ["éxito", "успех", "noun", "m"],
  ["unidad", "единица, подразделение", "noun", "f"],
  ["hielo", "лёд", "noun", "m"],
  ["matrimonio", "брак, супруги", "noun", "m"],
  ["piel", "кожа, шкура", "noun", "f"],
  ["arte", "искусство", "noun", "m"],
  ["común", "обычный, распространённый", "adjective"],
  ["intentar", "пытаться", "verb"],
  ["levantar", "поднимать", "verb"],
  ["brillante", "блестящий, яркий", "adjective"],
  ["visita", "визит, посещение", "noun", "f"],
  ["esperanza", "надежда", "noun", "f"],
  ["completo", "полный, целиком", "adjective"],
  ["trampa", "ловушка", "noun", "f"],
  ["monstruo", "чудовище", "noun", "m"],
  ["bajar", "спускать, опускать", "verb"],
  ["grandioso", "великолепный", "adjective"],
  ["socio", "партнёр, компаньон", "noun", "m"],
  ["herido", "раненый", "adjective"],
  ["caer", "падать", "verb"],
  ["escena", "сцена", "noun", "f"],
  ["mover", "двигать", "verb"],
  ["tema", "тема", "noun", "m"],
  ["preparado", "подготовленный", "adjective"],
  ["oeste", "запад", "noun", "m"],
  ["estupendo", "great, потрясающий", "adjective"],
  ["juicio", "суждение, судебный процесс", "noun", "m"],
  ["carga", "груз, нагрузка", "noun", "f"],
  ["banda", "банда, музыкальная группа", "noun", "f"],
  ["seguramente", "наверняка", "adverb"],
  ["majestad", "величество", "noun", "f"],
  ["enorme", "огромный", "adjective"],
  ["área", "область, площадь", "noun", "f"],
  ["ridículo", "смешной, нелепый", "adjective"],
  ["reloj", "часы", "noun", "m"],
  ["flor", "цветок", "noun", "f"],

  // --- 801-1000 ----------------------------------------------------------
  ["mapa", "карта", "noun", "m"],
  ["culpable", "виноватый", "adjective"],
  ["pareja", "пара (двое), партнёр", "noun", "f"],
  ["laboratorio", "лаборатория", "noun", "m"],
  ["beso", "поцелуй", "noun", "m"],
  ["cuestión", "вопрос (проблема), дело", "noun", "f"],
  ["perdonar", "прощать", "verb"],
  ["oscuridad", "темнота", "noun", "f"],
  ["televisión", "телевидение", "noun", "f"],
  ["prensa", "пресса", "noun", "f"],
  ["vistazo", "беглый взгляд", "noun", "m"],
  ["inmediatamente", "немедленно", "adverb"],
  ["solamente", "лишь, исключительно", "adverb"],
  ["gordo", "толстый", "adjective"],
  ["posibilidad", "вероятность, шанс", "noun", "f"],
  ["definitivamente", "окончательно, точно", "adverb"],
  ["cinta", "лента, плёнка", "noun", "f"],
  ["desear", "желать", "verb"],
  ["riesgo", "риск", "noun", "m"],
  ["cuento", "рассказ, сказка", "noun", "m"],
  ["sentimiento", "чувство", "noun", "m"],
  ["objetivo", "цель", "noun", "m"],
  ["arreglar", "чинить, улаживать", "verb"],
  ["casado", "женатый, замужняя", "adjective"],
  ["bote", "лодка, банка", "noun", "m"],
  ["proyecto", "проект", "noun", "m"],
  ["lana", "шерсть", "noun", "f"],
  ["pedazo", "кусок", "noun", "m"],
  ["absolutamente", "абсолютно", "adverb"],
  ["evitar", "избегать", "verb"],
  ["bala", "пуля", "noun", "f"],
  ["vosotros", "вы (нескольким, на «ты»)", "pronoun"],
  ["confianza", "доверие", "noun", "f"],
  ["especialmente", "особенно", "adverb"],
  ["comenzar", "начинать", "verb"],
  ["ruido", "шум", "noun", "m"],
  ["belleza", "красота", "noun", "f"],
  ["líder", "лидер", "noun", "m"],
  ["inocente", "невиновный, наивный", "adjective"],
  ["lástima", "жаль, жалость", "noun", "f"],
  ["enfermedad", "болезнь", "noun", "f"],
  ["central", "центральный", "adjective"],
  ["marcha", "ход, марш", "noun", "f"],
  ["justicia", "справедливость, правосудие", "noun", "f"],
  ["bello", "прекрасный", "adjective"],
  ["cabello", "волосы (на голове)", "noun", "m"],
  ["oscuro", "тёмный", "adjective"],
  ["embarazada", "беременная", "adjective"],
  ["costa", "побережье", "noun", "f"],
  ["dama", "дама", "noun", "f"],
  ["vos", "ты (ЛА)", "pronoun"],
  ["cura", "исцеление, священник", "noun", "f"],
  ["lengua", "язык", "noun", "f"],
  ["araña", "паук", "noun", "f"],
  ["voluntad", "воля", "noun", "f"],
  ["total", "итоговый, весь", "adjective"],
  ["dedo", "палец", "noun", "m"],
  ["agradecer", "благодарить", "verb"],
  ["partir", "уезжать, делить", "verb"],
  ["lucha", "борьба", "noun", "f"],
  ["copa", "бокал, кубок", "noun", "f"],
  ["destruir", "разрушать", "verb"],
  ["acceso", "доступ", "noun", "m"],
  ["desastre", "катастрофа", "noun", "m"],
  ["herida", "рана", "noun", "f"],
  ["naturaleza", "природа", "noun", "f"],
  ["luchar", "бороться", "verb"],
  ["imagen", "изображение, образ", "noun", "f"],
  ["varios", "несколько", "adjective"],
  ["auxilio", "спасите! выручка", "noun", "m"],
  ["sentar", "сажать, садиться", "verb"],
  ["responsable", "ответственный", "adjective"],
  ["sonido", "звук", "noun", "m"],
  ["escrito", "написанный", "adjective"],
  ["precioso", "драгоценный, прелестный", "adjective"],
  ["muestra", "образец, показ", "noun", "f"],
  ["fantasma", "призрак", "noun", "m"],
  ["profesional", "профессиональный", "adjective"],
  ["entero", "целый", "adjective"],
  ["dueño", "владелец, хозяин", "noun", "m"],
  ["tormenta", "буря, гроза", "noun", "f"],
  ["victoria", "победа", "noun", "f"],
  ["interior", "внутренний, нутро", "adjective"],
  ["piedra", "камень", "noun", "f"],
  ["militar", "военный", "adjective"],
  ["movimiento", "движение", "noun", "m"],
  ["familiar", "привычный, семейный", "adjective"],
  ["apartamento", "квартира", "noun", "m"],
  ["disparar", "стрелять", "verb"],
  ["tesoro", "сокровище", "noun", "m"],
  ["motivo", "мотив, повод", "noun", "m"],
  ["víctima", "жертва", "noun", "f"],
  ["diario", "ежедневный, дневник", "adjective"],
  ["descanso", "отдых, перерыв", "noun", "m"],
  ["quieto", "неподвижный, тихий", "adjective"],
  ["tamaño", "размер", "noun", "m"],
  ["colegio", "колледж, частная школа", "noun", "m"],
  ["cabo", "мыс, капрал", "noun", "m"],
  ["video", "видео", "noun", "m"],
  ["pelota", "мяч", "noun", "f"],
  ["directo", "прямой", "adjective"],
  ["estudio", "изучение, студия", "noun", "m"],
  ["grave", "серьёзный (о положении)", "adjective"],
  ["protección", "охрана, прикрытие", "noun", "f"],
  ["pecho", "грудь", "noun", "m"],
  ["costar", "стоить", "verb"],
  ["lago", "озеро", "noun", "m"],
  ["obviamente", "очевидно", "adverb"],
  ["robo", "кража", "noun", "m"],
  ["apoyo", "поддержка", "noun", "m"],
  ["imaginar", "воображать", "verb"],
  ["amenaza", "угроза", "noun", "f"],
  ["roto", "сломанный, порванный", "adjective"],
  ["piloto", "пилот", "noun", "m"],
  ["marca", "марка, отметка", "noun", "f"],
  ["combate", "бой", "noun", "m"],
  ["sección", "раздел, отдел", "noun", "f"],
  ["profundo", "глубокий", "adjective"],
  ["serie", "серия, сериал", "noun", "f"],
  ["contrato", "договор", "noun", "m"],
  ["americano", "американский", "adjective"],
  ["paseo", "прогулка", "noun", "m"],
  ["repente", "вдруг, внезапность", "noun", "m"],
  ["tropa", "войско, отряд", "noun", "f"],
  ["uso", "использование", "noun", "m"],
  ["distancia", "расстояние", "noun", "f"],
  ["averiguar", "выяснять", "verb"],
  ["actuar", "действовать, играть", "verb"],
  ["pulso", "пульс", "noun", "m"],
  ["elección", "выбор, выборы", "noun", "f"],
  ["sujeto", "субъект, тип", "noun", "m"],
  ["época", "эпоха, время года", "noun", "f"],
  ["pesar", "весить, сожаление", "verb"],
  ["gratis", "бесплатно", "adverb"],
  ["desaparecer", "исчезать", "verb"],
  ["empleo", "занятость, место работы", "noun", "m"],
  ["tumba", "могила", "noun", "f"],
  ["absoluto", "абсолютный", "adjective"],
  ["propiedad", "собственность", "noun", "f"],
  ["dormido", "спящий", "adjective"],
  ["castillo", "замок", "noun", "m"],
  ["dato", "данные, факт", "noun", "m"],
  ["torre", "башня", "noun", "f"],
  ["robar", "красть", "verb"],
  ["botella", "бутылка", "noun", "f"],
  ["testigo", "свидетель", "noun", "m"],
  ["presentar", "знакомить, представлять кого-то", "verb"],
  ["periódico", "газета", "noun", "m"],
  ["juez", "судья", "noun", "m"],
  ["milla", "миля", "noun", "f"],
  ["fuente", "источник, фонтан", "noun", "f"],
  ["genio", "гений, характер", "noun", "m"],
  ["alerta", "тревога, настороже", "noun", "f"],
  ["menor", "младший, меньший", "adjective"],
  ["explicar", "объяснять", "verb"],
  ["privado", "частный, личный", "adjective"],
  ["miembro", "член, участник", "noun", "m"],
  ["nacional", "национальный", "adjective"],
  ["discutir", "обсуждать, спорить", "verb"],
  ["detalle", "деталь, подробность", "noun", "m"],
];

/**
 * Feminine nouns beginning with a stressed "a" take the masculine article in
 * the singular: "el agua", never "la agua". The noun stays feminine.
 */
const TAKES_EL_DESPITE_FEMININE = new Set(["arma", "alma", "área", "hambre", "araña"]);

function withArticle(word: string, gender: "m" | "f"): string {
  const article = gender === "m" || TAKES_EL_DESPITE_FEMININE.has(word) ? "el" : "la";
  return `${article} ${word}`;
}

export const FREQUENCY_1000_LEXEMES: LexemeEntry[] = ROWS.map(([es, ru, pos, gender]) => ({
  // Built from the bare word, so adding or dropping an article later never
  // orphans the learner's progress on that card.
  id: `freq.${es.replace(/\s+/g, "_")}`,
  es: pos === "noun" && gender ? withArticle(es, gender) : es,
  ru: splitMeanings(ru),
  pos,
  // Rank is stamped later, from the one frequency order; `null` here would be
  // overwritten anyway, and duplicating the number in two files is how the two
  // of them drift apart.
  rank: null,
  cefr: "A2" as const,
  topics: ["frequency"],
  ...(gender ? { gender } : {}),
}));
