import type { VerbEntry } from "../domain/types";

/**
 * Verb inventory.
 *
 * Only what the rules cannot derive is stored: the infinitive, its Russian
 * meaning, and explicit `forms` overrides for irregular or spelling-changing
 * cells. Everything else is generated by `domain/conjugation`.
 *
 * `ruPresent` / `ruPastStem` fix the Russian cue where the Russian conjugator
 * would guess wrong (ходить → хожу, писать → пишу).
 */

/** Verbs whose only irregularity is the "c → qu / g → gu / z → c" preterite yo. */
function spellingPreterite(yo: string): VerbEntry["forms"] {
  return { preterite: { yo } };
}

export const REGULAR_AR_VERBS: VerbEntry[] = [
  { id: "v.hablar", infinitive: "hablar", ru: ["говорить"], group: "ar", cefr: "A1", rank: 118 },
  { id: "v.trabajar", infinitive: "trabajar", ru: ["работать"], group: "ar", cefr: "A1", rank: 402 },
  { id: "v.estudiar", infinitive: "estudiar", ru: ["учиться", "изучать"], group: "ar", cefr: "A1", rank: 611 },
  {
    id: "v.comprar",
    infinitive: "comprar",
    ru: ["покупать"],
    group: "ar",
    cefr: "A1",
    rank: 520,
    ruPresent: { yo: "покупаю", tu: "покупаешь", el: "покупает", nosotros: "покупаем", vosotros: "покупаете", ellos: "покупают" },
  },
  {
    id: "v.buscar",
    infinitive: "buscar",
    ru: ["искать"],
    group: "ar",
    cefr: "A1",
    rank: 233,
    forms: spellingPreterite("busqué"),
    ruPresent: { yo: "ищу", tu: "ищешь", el: "ищет", nosotros: "ищем", vosotros: "ищете", ellos: "ищут" },
    ruPastStem: "иска",
  },
  {
    id: "v.llegar",
    infinitive: "llegar",
    ru: ["приходить", "прибывать"],
    group: "ar",
    cefr: "A1",
    rank: 129,
    forms: spellingPreterite("llegué"),
    ruPresent: { yo: "прихожу", tu: "приходишь", el: "приходит", nosotros: "приходим", vosotros: "приходите", ellos: "приходят" },
    ruPastStem: "приходи",
  },
  { id: "v.pasar", infinitive: "pasar", ru: ["проходить", "случаться"], group: "ar", cefr: "A1", rank: 96, ruPresent: { yo: "прохожу", tu: "проходишь", el: "проходит", nosotros: "проходим", vosotros: "проходите", ellos: "проходят" }, ruPastStem: "проходи" },
  { id: "v.tomar", infinitive: "tomar", ru: ["брать", "пить"], group: "ar", cefr: "A1", rank: 189, ruPresent: { yo: "беру", tu: "берёшь", el: "берёт", nosotros: "берём", vosotros: "берёте", ellos: "берут" }, ruPastStem: "бра" },
  { id: "v.mirar", infinitive: "mirar", ru: ["смотреть"], group: "ar", cefr: "A1", rank: 214, ruPresent: { yo: "смотрю", tu: "смотришь", el: "смотрит", nosotros: "смотрим", vosotros: "смотрите", ellos: "смотрят" }, ruPastStem: "смотре" },
  // "llamar a alguien" is most often a phone call, and the complement below is
  // in the dative to match: "звонишь маме", not "зовёшь маме".
  { id: "v.llamar", infinitive: "llamar", ru: ["звонить", "звать"], group: "ar", cefr: "A1", rank: 176, ruPresent: { yo: "звоню", tu: "звонишь", el: "звонит", nosotros: "звоним", vosotros: "звоните", ellos: "звонят" }, ruPastStem: "звони" },
  { id: "v.dejar", infinitive: "dejar", ru: ["оставлять"], group: "ar", cefr: "A1", rank: 149 },
  { id: "v.quedar", infinitive: "quedar", ru: ["оставаться"], group: "ar", cefr: "A1", rank: 168, ruPresent: { yo: "остаюсь", tu: "остаёшься", el: "остаётся", nosotros: "остаёмся", vosotros: "остаётесь", ellos: "остаются" }, ruPastStem: "остава" },
  { id: "v.esperar", infinitive: "esperar", ru: ["ждать", "надеяться"], group: "ar", cefr: "A1", rank: 236, ruPresent: { yo: "жду", tu: "ждёшь", el: "ждёт", nosotros: "ждём", vosotros: "ждёте", ellos: "ждут" }, ruPastStem: "жда" },
  { id: "v.entrar", infinitive: "entrar", ru: ["входить"], group: "ar", cefr: "A1", rank: 262, ruPresent: { yo: "вхожу", tu: "входишь", el: "входит", nosotros: "входим", vosotros: "входите", ellos: "входят" }, ruPastStem: "входи" },
  { id: "v.ayudar", infinitive: "ayudar", ru: ["помогать"], group: "ar", cefr: "A1", rank: 428, ruPresent: { yo: "помогаю", tu: "помогаешь", el: "помогает", nosotros: "помогаем", vosotros: "помогаете", ellos: "помогают" } },
  { id: "v.necesitar", infinitive: "necesitar", ru: ["нуждаться"], group: "ar", cefr: "A1", rank: 391, ruPresent: { yo: "нуждаюсь", tu: "нуждаешься", el: "нуждается", nosotros: "нуждаемся", vosotros: "нуждаетесь", ellos: "нуждаются" } },
  { id: "v.usar", infinitive: "usar", ru: ["использовать"], group: "ar", cefr: "A1", rank: 559, ruPresent: { yo: "использую", tu: "используешь", el: "использует", nosotros: "используем", vosotros: "используете", ellos: "используют" }, ruPastStem: "использова" },
  { id: "v.cambiar", infinitive: "cambiar", ru: ["менять"], group: "ar", cefr: "A1", rank: 447, ruPresent: { yo: "меняю", tu: "меняешь", el: "меняет", nosotros: "меняем", vosotros: "меняете", ellos: "меняют" } },
  { id: "v.terminar", infinitive: "terminar", ru: ["заканчивать"], group: "ar", cefr: "A1", rank: 478, ruPresent: { yo: "заканчиваю", tu: "заканчиваешь", el: "заканчивает", nosotros: "заканчиваем", vosotros: "заканчиваете", ellos: "заканчивают" } },
  { id: "v.preguntar", infinitive: "preguntar", ru: ["спрашивать"], group: "ar", cefr: "A1", rank: 355, ruPresent: { yo: "спрашиваю", tu: "спрашиваешь", el: "спрашивает", nosotros: "спрашиваем", vosotros: "спрашиваете", ellos: "спрашивают" } },
  { id: "v.escuchar", infinitive: "escuchar", ru: ["слушать"], group: "ar", cefr: "A1", rank: 512, ruPresent: { yo: "слушаю", tu: "слушаешь", el: "слушает", nosotros: "слушаем", vosotros: "слушаете", ellos: "слушают" } },
  { id: "v.caminar", infinitive: "caminar", ru: ["ходить пешком"], group: "ar", cefr: "A1", rank: 903, ruPresent: { yo: "хожу пешком", tu: "ходишь пешком", el: "ходит пешком", nosotros: "ходим пешком", vosotros: "ходите пешком", ellos: "ходят пешком" }, ruPastStem: "ходи" },
  { id: "v.cantar", infinitive: "cantar", ru: ["петь"], group: "ar", cefr: "A1", rank: 866, ruPresent: { yo: "пою", tu: "поёшь", el: "поёт", nosotros: "поём", vosotros: "поёте", ellos: "поют" }, ruPastStem: "пе" },
  { id: "v.bailar", infinitive: "bailar", ru: ["танцевать"], group: "ar", cefr: "A1", rank: 1420, ruPresent: { yo: "танцую", tu: "танцуешь", el: "танцует", nosotros: "танцуем", vosotros: "танцуете", ellos: "танцуют" }, ruPastStem: "танцева" },
  { id: "v.cocinar", infinitive: "cocinar", ru: ["готовить еду"], group: "ar", cefr: "A1", rank: 1902, ruPresent: { yo: "готовлю", tu: "готовишь", el: "готовит", nosotros: "готовим", vosotros: "готовите", ellos: "готовят" }, ruPastStem: "готови" },
  { id: "v.viajar", infinitive: "viajar", ru: ["путешествовать"], group: "ar", cefr: "A1", rank: 1291, ruPresent: { yo: "путешествую", tu: "путешествуешь", el: "путешествует", nosotros: "путешествуем", vosotros: "путешествуете", ellos: "путешествуют" }, ruPastStem: "путешествова" },
  { id: "v.descansar", infinitive: "descansar", ru: ["отдыхать"], group: "ar", cefr: "A1", rank: 1707, ruPresent: { yo: "отдыхаю", tu: "отдыхаешь", el: "отдыхает", nosotros: "отдыхаем", vosotros: "отдыхаете", ellos: "отдыхают" } },
  { id: "v.limpiar", infinitive: "limpiar", ru: ["убирать", "чистить"], group: "ar", cefr: "A1", rank: 1543, ruPresent: { yo: "убираю", tu: "убираешь", el: "убирает", nosotros: "убираем", vosotros: "убираете", ellos: "убирают" } },
  { id: "v.ganar", infinitive: "ganar", ru: ["выигрывать", "зарабатывать"], group: "ar", cefr: "A1", rank: 597, ruPresent: { yo: "выигрываю", tu: "выигрываешь", el: "выигрывает", nosotros: "выигрываем", vosotros: "выигрываете", ellos: "выигрывают" } },
  { id: "v.olvidar", infinitive: "olvidar", ru: ["забывать"], group: "ar", cefr: "A1", rank: 664, ruPresent: { yo: "забываю", tu: "забываешь", el: "забывает", nosotros: "забываем", vosotros: "забываете", ellos: "забывают" } },
  { id: "v.contestar", infinitive: "contestar", ru: ["отвечать"], group: "ar", cefr: "A1", rank: 1611, ruPresent: { yo: "отвечаю", tu: "отвечаешь", el: "отвечает", nosotros: "отвечаем", vosotros: "отвечаете", ellos: "отвечают" } },
  { id: "v.invitar", infinitive: "invitar", ru: ["приглашать"], group: "ar", cefr: "A1", rank: 1385, ruPresent: { yo: "приглашаю", tu: "приглашаешь", el: "приглашает", nosotros: "приглашаем", vosotros: "приглашаете", ellos: "приглашают" } },
  { id: "v.visitar", infinitive: "visitar", ru: ["навещать", "посещать"], group: "ar", cefr: "A1", rank: 1132, ruPresent: { yo: "навещаю", tu: "навещаешь", el: "навещает", nosotros: "навещаем", vosotros: "навещаете", ellos: "навещают" } },
  { id: "v.nadar", infinitive: "nadar", ru: ["плавать"], group: "ar", cefr: "A1", rank: 2210, ruPresent: { yo: "плаваю", tu: "плаваешь", el: "плавает", nosotros: "плаваем", vosotros: "плаваете", ellos: "плавают" } },
  { id: "v.lavar", infinitive: "lavar", ru: ["мыть", "стирать"], group: "ar", cefr: "A1", rank: 1988, ruPresent: { yo: "мою", tu: "моешь", el: "моет", nosotros: "моем", vosotros: "моете", ellos: "моют" }, ruPastStem: "мы" },
  { id: "v.mandar", infinitive: "mandar", ru: ["посылать"], group: "ar", cefr: "A1", rank: 748, ruPresent: { yo: "посылаю", tu: "посылаешь", el: "посылает", nosotros: "посылаем", vosotros: "посылаете", ellos: "посылают" } },
  { id: "v.parar", infinitive: "parar", ru: ["останавливать"], group: "ar", cefr: "A1", rank: 690, ruPresent: { yo: "останавливаю", tu: "останавливаешь", el: "останавливает", nosotros: "останавливаем", vosotros: "останавливаете", ellos: "останавливают" } },
  { id: "v.tratar", infinitive: "tratar", ru: ["пытаться", "обращаться"], group: "ar", cefr: "A1", rank: 305, ruPresent: { yo: "пытаюсь", tu: "пытаешься", el: "пытается", nosotros: "пытаемся", vosotros: "пытаетесь", ellos: "пытаются" } },
  {
    id: "v.sacar",
    infinitive: "sacar",
    ru: ["доставать", "вынимать"],
    group: "ar",
    cefr: "A1",
    rank: 470,
    forms: spellingPreterite("saqué"),
    ruPresent: { yo: "достаю", tu: "достаёшь", el: "достаёт", nosotros: "достаём", vosotros: "достаёте", ellos: "достают" },
    ruPastStem: "достава",
  },
  {
    id: "v.pagar",
    infinitive: "pagar",
    ru: ["платить"],
    group: "ar",
    cefr: "A1",
    rank: 703,
    forms: spellingPreterite("pagué"),
    ruPresent: { yo: "плачу", tu: "платишь", el: "платит", nosotros: "платим", vosotros: "платите", ellos: "платят" },
    ruPastStem: "плати",
  },
];

export const REGULAR_ER_VERBS: VerbEntry[] = [
  { id: "v.comer", infinitive: "comer", ru: ["есть", "кушать"], group: "er", cefr: "A1", rank: 522, ruPresent: { yo: "ем", tu: "ешь", el: "ест", nosotros: "едим", vosotros: "едите", ellos: "едят" }, ruPastStem: "е" },
  { id: "v.beber", infinitive: "beber", ru: ["пить"], group: "er", cefr: "A1", rank: 1264, ruPresent: { yo: "пью", tu: "пьёшь", el: "пьёт", nosotros: "пьём", vosotros: "пьёте", ellos: "пьют" }, ruPastStem: "пи" },
  { id: "v.aprender", infinitive: "aprender", ru: ["учить", "усваивать"], group: "er", cefr: "A1", rank: 837, ruPresent: { yo: "учу", tu: "учишь", el: "учит", nosotros: "учим", vosotros: "учите", ellos: "учат" }, ruPastStem: "учи" },
  { id: "v.comprender", infinitive: "comprender", ru: ["понимать"], group: "er", cefr: "A1", rank: 719, ruPresent: { yo: "понимаю", tu: "понимаешь", el: "понимает", nosotros: "понимаем", vosotros: "понимаете", ellos: "понимают" } },
  { id: "v.correr", infinitive: "correr", ru: ["бегать"], group: "er", cefr: "A1", rank: 640, ruPresent: { yo: "бегаю", tu: "бегаешь", el: "бегает", nosotros: "бегаем", vosotros: "бегаете", ellos: "бегают" } },
  {
    id: "v.leer",
    infinitive: "leer",
    ru: ["читать"],
    group: "er",
    cefr: "A1",
    rank: 588,
    forms: { preterite: { el: "leyó", ellos: "leyeron" } },
    ruPresent: { yo: "читаю", tu: "читаешь", el: "читает", nosotros: "читаем", vosotros: "читаете", ellos: "читают" },
  },
  {
    id: "v.creer",
    infinitive: "creer",
    ru: ["верить", "считать"],
    group: "er",
    cefr: "A1",
    rank: 158,
    forms: { preterite: { el: "creyó", ellos: "creyeron" } },
    ruPresent: { yo: "верю", tu: "веришь", el: "верит", nosotros: "верим", vosotros: "верите", ellos: "верят" },
    ruPastStem: "вери",
  },
  { id: "v.vender", infinitive: "vender", ru: ["продавать"], group: "er", cefr: "A1", rank: 1058, ruPresent: { yo: "продаю", tu: "продаёшь", el: "продаёт", nosotros: "продаём", vosotros: "продаёте", ellos: "продают" }, ruPastStem: "продава" },
  { id: "v.deber", infinitive: "deber", ru: ["быть должным"], group: "er", cefr: "A1", rank: 288, ruPresent: { yo: "должен(на)", tu: "должен(на)", el: "должен", nosotros: "должны", vosotros: "должны", ellos: "должны" }, ruPast: { yo: "был(а) должен(на)", tu: "был(а) должен(на)", el: "был должен", nosotros: "были должны", vosotros: "были должны", ellos: "были должны" } },
  { id: "v.responder", infinitive: "responder", ru: ["отвечать"], group: "er", cefr: "A1", rank: 601, ruPresent: { yo: "отвечаю", tu: "отвечаешь", el: "отвечает", nosotros: "отвечаем", vosotros: "отвечаете", ellos: "отвечают" } },
  { id: "v.romper", infinitive: "romper", ru: ["ломать", "рвать"], group: "er", cefr: "A1", rank: 1195, ruPresent: { yo: "ломаю", tu: "ломаешь", el: "ломает", nosotros: "ломаем", vosotros: "ломаете", ellos: "ломают" } },
  { id: "v.prometer", infinitive: "prometer", ru: ["обещать"], group: "er", cefr: "A2", rank: 1338, ruPresent: { yo: "обещаю", tu: "обещаешь", el: "обещает", nosotros: "обещаем", vosotros: "обещаете", ellos: "обещают" } },
  { id: "v.temer", infinitive: "temer", ru: ["бояться"], group: "er", cefr: "A2", rank: 1544, ruPresent: { yo: "боюсь", tu: "боишься", el: "боится", nosotros: "боимся", vosotros: "боитесь", ellos: "боятся" }, ruPastStem: "боя" },
  { id: "v.esconder", infinitive: "esconder", ru: ["прятать"], group: "er", cefr: "A2", rank: 1832, ruPresent: { yo: "прячу", tu: "прячешь", el: "прячет", nosotros: "прячем", vosotros: "прячете", ellos: "прячут" }, ruPastStem: "прята" },
  { id: "v.sorprender", infinitive: "sorprender", ru: ["удивлять"], group: "er", cefr: "A2", rank: 1450, ruPresent: { yo: "удивляю", tu: "удивляешь", el: "удивляет", nosotros: "удивляем", vosotros: "удивляете", ellos: "удивляют" } },
  { id: "v.depender", infinitive: "depender", ru: ["зависеть"], group: "er", cefr: "A2", rank: 1023, ruPresent: { yo: "завишу", tu: "зависишь", el: "зависит", nosotros: "зависим", vosotros: "зависите", ellos: "зависят" }, ruPastStem: "зависе" },
  { id: "v.suceder", infinitive: "suceder", ru: ["происходить"], group: "er", cefr: "A2", rank: 909, ruPresent: { yo: "происхожу", tu: "происходишь", el: "происходит", nosotros: "происходим", vosotros: "происходите", ellos: "происходят" }, ruPastStem: "происходи" },
  { id: "v.barrer", infinitive: "barrer", ru: ["подметать"], group: "er", cefr: "A2", rank: 3104, ruPresent: { yo: "подметаю", tu: "подметаешь", el: "подметает", nosotros: "подметаем", vosotros: "подметаете", ellos: "подметают" } },
  { id: "v.toser", infinitive: "toser", ru: ["кашлять"], group: "er", cefr: "A2", rank: 3860, ruPresent: { yo: "кашляю", tu: "кашляешь", el: "кашляет", nosotros: "кашляем", vosotros: "кашляете", ellos: "кашляют" } },
  { id: "v.cometer", infinitive: "cometer", ru: ["совершать"], group: "er", cefr: "A2", rank: 1476, ruPresent: { yo: "совершаю", tu: "совершаешь", el: "совершает", nosotros: "совершаем", vosotros: "совершаете", ellos: "совершают" } },
  { id: "v.aparecer", infinitive: "aparecer", ru: ["появляться"], group: "er", cefr: "A2", rank: 654, forms: { present: { yo: "aparezco" } }, ruPresent: { yo: "появляюсь", tu: "появляешься", el: "появляется", nosotros: "появляемся", vosotros: "появляетесь", ellos: "появляются" } },
  { id: "v.ofrecer", infinitive: "ofrecer", ru: ["предлагать"], group: "er", cefr: "A2", rank: 726, forms: { present: { yo: "ofrezco" } }, ruPresent: { yo: "предлагаю", tu: "предлагаешь", el: "предлагает", nosotros: "предлагаем", vosotros: "предлагаете", ellos: "предлагают" } },
  { id: "v.merecer", infinitive: "merecer", ru: ["заслуживать"], group: "er", cefr: "A2", rank: 1211, forms: { present: { yo: "merezco" } }, ruPresent: { yo: "заслуживаю", tu: "заслуживаешь", el: "заслуживает", nosotros: "заслуживаем", vosotros: "заслуживаете", ellos: "заслуживают" } },
  { id: "v.pertenecer", infinitive: "pertenecer", ru: ["принадлежать"], group: "er", cefr: "A2", rank: 1791, forms: { present: { yo: "pertenezco" } }, ruPresent: { yo: "принадлежу", tu: "принадлежишь", el: "принадлежит", nosotros: "принадлежим", vosotros: "принадлежите", ellos: "принадлежат" }, ruPastStem: "принадлежа" },
  { id: "v.recoger", infinitive: "recoger", ru: ["забирать", "собирать"], group: "er", cefr: "A2", rank: 1140, forms: { present: { yo: "recojo" } }, ruPresent: { yo: "забираю", tu: "забираешь", el: "забирает", nosotros: "забираем", vosotros: "забираете", ellos: "забирают" } },
  { id: "v.escoger", infinitive: "escoger", ru: ["выбирать"], group: "er", cefr: "A2", rank: 1583, forms: { present: { yo: "escojo" } }, ruPresent: { yo: "выбираю", tu: "выбираешь", el: "выбирает", nosotros: "выбираем", vosotros: "выбираете", ellos: "выбирают" } },
  { id: "v.proteger", infinitive: "proteger", ru: ["защищать"], group: "er", cefr: "A2", rank: 1216, forms: { present: { yo: "protejo" } }, ruPresent: { yo: "защищаю", tu: "защищаешь", el: "защищает", nosotros: "защищаем", vosotros: "защищаете", ellos: "защищают" } },
  { id: "v.meter", infinitive: "meter", ru: ["класть", "совать"], group: "er", cefr: "A2", rank: 1073, ruPresent: { yo: "кладу", tu: "кладёшь", el: "кладёт", nosotros: "кладём", vosotros: "кладёте", ellos: "кладут" }, ruPastStem: "кла" },
  { id: "v.recorrer", infinitive: "recorrer", ru: ["обходить", "объезжать"], group: "er", cefr: "A2", rank: 1927, ruPresent: { yo: "обхожу", tu: "обходишь", el: "обходит", nosotros: "обходим", vosotros: "обходите", ellos: "обходят" }, ruPastStem: "обходи" },
  { id: "v.exceder", infinitive: "exceder", ru: ["превышать"], group: "er", cefr: "A2", rank: 3450, ruPresent: { yo: "превышаю", tu: "превышаешь", el: "превышает", nosotros: "превышаем", vosotros: "превышаете", ellos: "превышают" } },
];

export const REGULAR_IR_VERBS: VerbEntry[] = [
  { id: "v.vivir", infinitive: "vivir", ru: ["жить"], group: "ir", cefr: "A1", rank: 293, ruPresent: { yo: "живу", tu: "живёшь", el: "живёт", nosotros: "живём", vosotros: "живёте", ellos: "живут" }, ruPastStem: "жи" },
  { id: "v.escribir", infinitive: "escribir", ru: ["писать"], group: "ir", cefr: "A1", rank: 486, ruPresent: { yo: "пишу", tu: "пишешь", el: "пишет", nosotros: "пишем", vosotros: "пишете", ellos: "пишут" }, ruPastStem: "писа" },
  { id: "v.abrir", infinitive: "abrir", ru: ["открывать"], group: "ir", cefr: "A1", rank: 456, ruPresent: { yo: "открываю", tu: "открываешь", el: "открывает", nosotros: "открываем", vosotros: "открываете", ellos: "открывают" } },
  { id: "v.recibir", infinitive: "recibir", ru: ["получать"], group: "ir", cefr: "A1", rank: 578, ruPresent: { yo: "получаю", tu: "получаешь", el: "получает", nosotros: "получаем", vosotros: "получаете", ellos: "получают" } },
  { id: "v.subir", infinitive: "subir", ru: ["подниматься"], group: "ir", cefr: "A1", rank: 671, ruPresent: { yo: "поднимаюсь", tu: "поднимаешься", el: "поднимается", nosotros: "поднимаемся", vosotros: "поднимаетесь", ellos: "поднимаются" } },
  { id: "v.decidir", infinitive: "decidir", ru: ["решать"], group: "ir", cefr: "A1", rank: 553, ruPresent: { yo: "решаю", tu: "решаешь", el: "решает", nosotros: "решаем", vosotros: "решаете", ellos: "решают" } },
  { id: "v.permitir", infinitive: "permitir", ru: ["разрешать"], group: "ir", cefr: "A2", rank: 631, ruPresent: { yo: "разрешаю", tu: "разрешаешь", el: "разрешает", nosotros: "разрешаем", vosotros: "разрешаете", ellos: "разрешают" } },
  { id: "v.describir", infinitive: "describir", ru: ["описывать"], group: "ir", cefr: "A2", rank: 1364, ruPresent: { yo: "описываю", tu: "описываешь", el: "описывает", nosotros: "описываем", vosotros: "описываете", ellos: "описывают" } },
  { id: "v.existir", infinitive: "existir", ru: ["существовать"], group: "ir", cefr: "A2", rank: 683, ruPresent: { yo: "существую", tu: "существуешь", el: "существует", nosotros: "существуем", vosotros: "существуете", ellos: "существуют" }, ruPastStem: "существова" },
  { id: "v.sufrir", infinitive: "sufrir", ru: ["страдать"], group: "ir", cefr: "A2", rank: 858, ruPresent: { yo: "страдаю", tu: "страдаешь", el: "страдает", nosotros: "страдаем", vosotros: "страдаете", ellos: "страдают" } },
];

/**
 * Irregular verbs. Every deviating cell is spelled out; the rest still comes
 * from the regular rules, so the tables stay short and reviewable.
 */
export const IRREGULAR_VERBS: VerbEntry[] = [
  {
    id: "v.ser",
    infinitive: "ser",
    ru: ["быть"],
    group: "er",
    cefr: "A1",
    rank: 6,
    irregular: true,
    forms: {
      // `sos` is the one voseo form the general rule cannot produce.
      present: { yo: "soy", tu: "eres", vos: "sos", el: "es", nosotros: "somos", vosotros: "sois", ellos: "son" },
      preterite: { yo: "fui", tu: "fuiste", el: "fue", nosotros: "fuimos", vosotros: "fuisteis", ellos: "fueron" },
      imperfect: { yo: "era", tu: "eras", el: "era", nosotros: "éramos", vosotros: "erais", ellos: "eran" },
    },
    /*
     * Empty on purpose. Russian drops the present-tense copula altogether:
     * "Я врач", "Ты не отсюда", "Вы студенты?". Filling it with "являюсь"
     * produced stilted cues and outright broken ones — "Я не являюсь отсюда".
     * The past tense does have a copula, and `ruPast` below supplies it.
     */
    ruPresent: { yo: "", tu: "", el: "", nosotros: "", vosotros: "", ellos: "" },
    ruPast: { yo: "был(а)", tu: "был(а)", el: "был", nosotros: "были", vosotros: "были", ellos: "были" },
  },
  {
    id: "v.estar",
    infinitive: "estar",
    ru: ["находиться", "быть"],
    group: "ar",
    cefr: "A1",
    rank: 32,
    irregular: true,
    forms: {
      present: { yo: "estoy", tu: "estás", el: "está", nosotros: "estamos", vosotros: "estáis", ellos: "están" },
      preterite: { yo: "estuve", tu: "estuviste", el: "estuvo", nosotros: "estuvimos", vosotros: "estuvisteis", ellos: "estuvieron" },
    },
    ruPresent: { yo: "нахожусь", tu: "находишься", el: "находится", nosotros: "находимся", vosotros: "находитесь", ellos: "находятся" },
    ruPastStem: "находи",
  },
  {
    id: "v.ir",
    infinitive: "ir",
    ru: ["идти", "ехать"],
    group: "ir",
    cefr: "A1",
    rank: 26,
    irregular: true,
    forms: {
      // Voseo keeps `vas` here rather than deriving a form from the infinitive.
      present: { yo: "voy", tu: "vas", vos: "vas", el: "va", nosotros: "vamos", vosotros: "vais", ellos: "van" },
      preterite: { yo: "fui", tu: "fuiste", el: "fue", nosotros: "fuimos", vosotros: "fuisteis", ellos: "fueron" },
      imperfect: { yo: "iba", tu: "ibas", el: "iba", nosotros: "íbamos", vosotros: "ibais", ellos: "iban" },
    },
    ruPresent: { yo: "иду", tu: "идёшь", el: "идёт", nosotros: "идём", vosotros: "идёте", ellos: "идут" },
    ruPast: { yo: "шёл (шла)", tu: "шёл (шла)", el: "шёл", nosotros: "шли", vosotros: "шли", ellos: "шли" },
  },
  {
    id: "v.tener",
    infinitive: "tener",
    ru: ["иметь"],
    group: "er",
    cefr: "A1",
    rank: 24,
    irregular: true,
    forms: {
      present: { yo: "tengo", tu: "tienes", el: "tiene", nosotros: "tenemos", vosotros: "tenéis", ellos: "tienen" },
      preterite: { yo: "tuve", tu: "tuviste", el: "tuvo", nosotros: "tuvimos", vosotros: "tuvisteis", ellos: "tuvieron" },
      future: { yo: "tendré", tu: "tendrás", el: "tendrá", nosotros: "tendremos", vosotros: "tendréis", ellos: "tendrán" },
    },
    ruPresent: { yo: "имею", tu: "имеешь", el: "имеет", nosotros: "имеем", vosotros: "имеете", ellos: "имеют" },
  },
  {
    id: "v.hacer",
    infinitive: "hacer",
    ru: ["делать"],
    group: "er",
    cefr: "A1",
    rank: 40,
    irregular: true,
    forms: {
      present: { yo: "hago" },
      preterite: { yo: "hice", tu: "hiciste", el: "hizo", nosotros: "hicimos", vosotros: "hicisteis", ellos: "hicieron" },
      future: { yo: "haré", tu: "harás", el: "hará", nosotros: "haremos", vosotros: "haréis", ellos: "harán" },
    },
    ruPresent: { yo: "делаю", tu: "делаешь", el: "делает", nosotros: "делаем", vosotros: "делаете", ellos: "делают" },
  },
  {
    id: "v.poder",
    infinitive: "poder",
    ru: ["мочь"],
    group: "er",
    cefr: "A1",
    rank: 30,
    irregular: true,
    forms: {
      present: { yo: "puedo", tu: "puedes", el: "puede", ellos: "pueden" },
      preterite: { yo: "pude", tu: "pudiste", el: "pudo", nosotros: "pudimos", vosotros: "pudisteis", ellos: "pudieron" },
      future: { yo: "podré", tu: "podrás", el: "podrá", nosotros: "podremos", vosotros: "podréis", ellos: "podrán" },
    },
    ruPresent: { yo: "могу", tu: "можешь", el: "может", nosotros: "можем", vosotros: "можете", ellos: "могут" },
    ruPast: { yo: "мог(ла)", tu: "мог(ла)", el: "мог", nosotros: "могли", vosotros: "могли", ellos: "могли" },
  },
  {
    id: "v.querer",
    infinitive: "querer",
    ru: ["хотеть", "любить"],
    group: "er",
    cefr: "A1",
    rank: 51,
    irregular: true,
    forms: {
      present: { yo: "quiero", tu: "quieres", el: "quiere", ellos: "quieren" },
      preterite: { yo: "quise", tu: "quisiste", el: "quiso", nosotros: "quisimos", vosotros: "quisisteis", ellos: "quisieron" },
      future: { yo: "querré", tu: "querrás", el: "querrá", nosotros: "querremos", vosotros: "querréis", ellos: "querrán" },
    },
    ruPresent: { yo: "хочу", tu: "хочешь", el: "хочет", nosotros: "хотим", vosotros: "хотите", ellos: "хотят" },
    ruPastStem: "хоте",
  },
  {
    id: "v.decir",
    infinitive: "decir",
    ru: ["говорить", "сказать"],
    group: "ir",
    cefr: "A1",
    rank: 21,
    irregular: true,
    forms: {
      present: { yo: "digo", tu: "dices", el: "dice", nosotros: "decimos", vosotros: "decís", ellos: "dicen" },
      preterite: { yo: "dije", tu: "dijiste", el: "dijo", nosotros: "dijimos", vosotros: "dijisteis", ellos: "dijeron" },
      future: { yo: "diré", tu: "dirás", el: "dirá", nosotros: "diremos", vosotros: "diréis", ellos: "dirán" },
    },
    ruPresent: { yo: "говорю", tu: "говоришь", el: "говорит", nosotros: "говорим", vosotros: "говорите", ellos: "говорят" },
    ruPastStem: "говори",
  },
  {
    id: "v.venir",
    infinitive: "venir",
    ru: ["приходить"],
    group: "ir",
    cefr: "A1",
    rank: 89,
    irregular: true,
    forms: {
      present: { yo: "vengo", tu: "vienes", el: "viene", nosotros: "venimos", vosotros: "venís", ellos: "vienen" },
      preterite: { yo: "vine", tu: "viniste", el: "vino", nosotros: "vinimos", vosotros: "vinisteis", ellos: "vinieron" },
      future: { yo: "vendré", tu: "vendrás", el: "vendrá", nosotros: "vendremos", vosotros: "vendréis", ellos: "vendrán" },
    },
    ruPresent: { yo: "прихожу", tu: "приходишь", el: "приходит", nosotros: "приходим", vosotros: "приходите", ellos: "приходят" },
    ruPastStem: "приходи",
  },
  {
    id: "v.ver",
    infinitive: "ver",
    ru: ["видеть"],
    group: "er",
    cefr: "A1",
    rank: 44,
    irregular: true,
    forms: {
      present: { yo: "veo" },
      preterite: { yo: "vi", el: "vio" },
      imperfect: { yo: "veía", tu: "veías", el: "veía", nosotros: "veíamos", vosotros: "veíais", ellos: "veían" },
    },
    ruPresent: { yo: "вижу", tu: "видишь", el: "видит", nosotros: "видим", vosotros: "видите", ellos: "видят" },
    ruPastStem: "виде",
  },
  {
    id: "v.dar",
    infinitive: "dar",
    ru: ["давать"],
    group: "ar",
    cefr: "A1",
    rank: 57,
    irregular: true,
    forms: {
      present: { yo: "doy", vosotros: "dais" },
      preterite: { yo: "di", tu: "diste", el: "dio", nosotros: "dimos", vosotros: "disteis", ellos: "dieron" },
    },
    ruPresent: { yo: "даю", tu: "даёшь", el: "даёт", nosotros: "даём", vosotros: "даёте", ellos: "дают" },
    ruPastStem: "дава",
  },
  {
    id: "v.saber",
    infinitive: "saber",
    ru: ["знать", "уметь"],
    group: "er",
    cefr: "A1",
    rank: 55,
    irregular: true,
    forms: {
      present: { yo: "sé" },
      preterite: { yo: "supe", tu: "supiste", el: "supo", nosotros: "supimos", vosotros: "supisteis", ellos: "supieron" },
      future: { yo: "sabré", tu: "sabrás", el: "sabrá", nosotros: "sabremos", vosotros: "sabréis", ellos: "sabrán" },
    },
    ruPresent: { yo: "знаю", tu: "знаешь", el: "знает", nosotros: "знаем", vosotros: "знаете", ellos: "знают" },
  },
  {
    id: "v.poner",
    infinitive: "poner",
    ru: ["класть", "ставить"],
    group: "er",
    cefr: "A1",
    rank: 105,
    irregular: true,
    forms: {
      present: { yo: "pongo" },
      preterite: { yo: "puse", tu: "pusiste", el: "puso", nosotros: "pusimos", vosotros: "pusisteis", ellos: "pusieron" },
      future: { yo: "pondré", tu: "pondrás", el: "pondrá", nosotros: "pondremos", vosotros: "pondréis", ellos: "pondrán" },
    },
    ruPresent: { yo: "кладу", tu: "кладёшь", el: "кладёт", nosotros: "кладём", vosotros: "кладёте", ellos: "кладут" },
    ruPastStem: "кла",
  },
  {
    id: "v.salir",
    infinitive: "salir",
    ru: ["выходить"],
    group: "ir",
    cefr: "A1",
    rank: 152,
    irregular: true,
    forms: {
      present: { yo: "salgo" },
      future: { yo: "saldré", tu: "saldrás", el: "saldrá", nosotros: "saldremos", vosotros: "saldréis", ellos: "saldrán" },
    },
    ruPresent: { yo: "выхожу", tu: "выходишь", el: "выходит", nosotros: "выходим", vosotros: "выходите", ellos: "выходят" },
    ruPastStem: "выходи",
  },
  {
    id: "v.traer",
    infinitive: "traer",
    ru: ["приносить"],
    group: "er",
    cefr: "A2",
    rank: 344,
    irregular: true,
    forms: {
      present: { yo: "traigo" },
      preterite: { yo: "traje", tu: "trajiste", el: "trajo", nosotros: "trajimos", vosotros: "trajisteis", ellos: "trajeron" },
    },
    ruPresent: { yo: "приношу", tu: "приносишь", el: "приносит", nosotros: "приносим", vosotros: "приносите", ellos: "приносят" },
    ruPastStem: "приноси",
  },
  {
    id: "v.conocer",
    infinitive: "conocer",
    ru: ["знать", "быть знакомым"],
    group: "er",
    cefr: "A1",
    rank: 190,
    irregular: true,
    forms: { present: { yo: "conozco" } },
    ruPresent: { yo: "знаю", tu: "знаешь", el: "знает", nosotros: "знаем", vosotros: "знаете", ellos: "знают" },
  },
  {
    id: "v.pensar",
    infinitive: "pensar",
    ru: ["думать"],
    group: "ar",
    cefr: "A1",
    rank: 145,
    irregular: true,
    forms: { present: { yo: "pienso", tu: "piensas", el: "piensa", ellos: "piensan" } },
    ruPresent: { yo: "думаю", tu: "думаешь", el: "думает", nosotros: "думаем", vosotros: "думаете", ellos: "думают" },
  },
  {
    id: "v.empezar",
    infinitive: "empezar",
    ru: ["начинать"],
    group: "ar",
    cefr: "A1",
    rank: 425,
    irregular: true,
    forms: {
      present: { yo: "empiezo", tu: "empiezas", el: "empieza", ellos: "empiezan" },
      preterite: { yo: "empecé" },
    },
    ruPresent: { yo: "начинаю", tu: "начинаешь", el: "начинает", nosotros: "начинаем", vosotros: "начинаете", ellos: "начинают" },
  },
  {
    id: "v.volver",
    infinitive: "volver",
    ru: ["возвращаться"],
    group: "er",
    cefr: "A1",
    rank: 199,
    irregular: true,
    forms: { present: { yo: "vuelvo", tu: "vuelves", el: "vuelve", ellos: "vuelven" } },
    ruPresent: { yo: "возвращаюсь", tu: "возвращаешься", el: "возвращается", nosotros: "возвращаемся", vosotros: "возвращаетесь", ellos: "возвращаются" },
    ruPast: { yo: "возвращался(ась)", tu: "возвращался(ась)", el: "возвращался", nosotros: "возвращались", vosotros: "возвращались", ellos: "возвращались" },
  },
  {
    id: "v.dormir",
    infinitive: "dormir",
    ru: ["спать"],
    group: "ir",
    cefr: "A1",
    rank: 745,
    irregular: true,
    forms: {
      present: { yo: "duermo", tu: "duermes", el: "duerme", ellos: "duermen" },
      preterite: { el: "durmió", ellos: "durmieron" },
    },
    ruPresent: { yo: "сплю", tu: "спишь", el: "спит", nosotros: "спим", vosotros: "спите", ellos: "спят" },
    ruPastStem: "спа",
  },
  {
    id: "v.pedir",
    infinitive: "pedir",
    ru: ["просить", "заказывать"],
    group: "ir",
    cefr: "A1",
    rank: 351,
    irregular: true,
    forms: {
      present: { yo: "pido", tu: "pides", el: "pide", ellos: "piden" },
      preterite: { el: "pidió", ellos: "pidieron" },
    },
    ruPresent: { yo: "прошу", tu: "просишь", el: "просит", nosotros: "просим", vosotros: "просите", ellos: "просят" },
    ruPastStem: "проси",
  },
  {
    id: "v.encontrar",
    infinitive: "encontrar",
    ru: ["находить"],
    group: "ar",
    cefr: "A1",
    rank: 224,
    irregular: true,
    forms: { present: { yo: "encuentro", tu: "encuentras", el: "encuentra", ellos: "encuentran" } },
    ruPresent: { yo: "нахожу", tu: "находишь", el: "находит", nosotros: "находим", vosotros: "находите", ellos: "находят" },
    ruPastStem: "находи",
  },
  {
    id: "v.entender",
    infinitive: "entender",
    ru: ["понимать"],
    group: "er",
    cefr: "A1",
    rank: 396,
    irregular: true,
    forms: { present: { yo: "entiendo", tu: "entiendes", el: "entiende", ellos: "entienden" } },
    ruPresent: { yo: "понимаю", tu: "понимаешь", el: "понимает", nosotros: "понимаем", vosotros: "понимаете", ellos: "понимают" },
  },
  {
    id: "v.jugar",
    infinitive: "jugar",
    ru: ["играть"],
    group: "ar",
    cefr: "A1",
    rank: 613,
    irregular: true,
    forms: {
      present: { yo: "juego", tu: "juegas", el: "juega", ellos: "juegan" },
      preterite: { yo: "jugué" },
    },
    ruPresent: { yo: "играю", tu: "играешь", el: "играет", nosotros: "играем", vosotros: "играете", ellos: "играют" },
  },
  {
    id: "v.oir",
    infinitive: "oír",
    ru: ["слышать"],
    group: "ir",
    cefr: "A1",
    rank: 271,
    irregular: true,
    forms: {
      present: { yo: "oigo", tu: "oyes", el: "oye", nosotros: "oímos", vosotros: "oís", ellos: "oyen" },
      preterite: { yo: "oí", el: "oyó", ellos: "oyeron" },
    },
    ruPresent: { yo: "слышу", tu: "слышишь", el: "слышит", nosotros: "слышим", vosotros: "слышите", ellos: "слышат" },
    ruPastStem: "слыша",
  },
  {
    id: "v.cerrar",
    infinitive: "cerrar",
    ru: ["закрывать"],
    group: "ar",
    cefr: "A1",
    rank: 776,
    irregular: true,
    forms: { present: { yo: "cierro", tu: "cierras", el: "cierra", ellos: "cierran" } },
    ruPresent: { yo: "закрываю", tu: "закрываешь", el: "закрывает", nosotros: "закрываем", vosotros: "закрываете", ellos: "закрывают" },
  },
  {
    id: "v.perder",
    infinitive: "perder",
    ru: ["терять"],
    group: "er",
    cefr: "A1",
    rank: 383,
    irregular: true,
    forms: { present: { yo: "pierdo", tu: "pierdes", el: "pierde", ellos: "pierden" } },
    ruPresent: { yo: "теряю", tu: "теряешь", el: "теряет", nosotros: "теряем", vosotros: "теряете", ellos: "теряют" },
  },
  {
    id: "v.recordar",
    infinitive: "recordar",
    ru: ["помнить", "вспоминать"],
    group: "ar",
    cefr: "A1",
    rank: 434,
    irregular: true,
    forms: { present: { yo: "recuerdo", tu: "recuerdas", el: "recuerda", ellos: "recuerdan" } },
    ruPresent: { yo: "помню", tu: "помнишь", el: "помнит", nosotros: "помним", vosotros: "помните", ellos: "помнят" },
    ruPastStem: "помни",
  },
  {
    id: "v.seguir",
    infinitive: "seguir",
    ru: ["следовать", "продолжать"],
    group: "ir",
    cefr: "A2",
    rank: 195,
    irregular: true,
    forms: {
      present: { yo: "sigo", tu: "sigues", el: "sigue", nosotros: "seguimos", vosotros: "seguís", ellos: "siguen" },
      preterite: { el: "siguió", ellos: "siguieron" },
    },
    ruPresent: { yo: "следую", tu: "следуешь", el: "следует", nosotros: "следуем", vosotros: "следуете", ellos: "следуют" },
    ruPastStem: "следова",
  },
  {
    id: "v.sentir",
    infinitive: "sentir",
    ru: ["чувствовать"],
    group: "ir",
    cefr: "A2",
    rank: 259,
    irregular: true,
    forms: {
      present: { yo: "siento", tu: "sientes", el: "siente", ellos: "sienten" },
      preterite: { el: "sintió", ellos: "sintieron" },
    },
    ruPresent: { yo: "чувствую", tu: "чувствуешь", el: "чувствует", nosotros: "чувствуем", vosotros: "чувствуете", ellos: "чувствуют" },
    ruPastStem: "чувствова",
  },
];

export const ALL_VERBS: VerbEntry[] = [
  ...REGULAR_AR_VERBS,
  ...REGULAR_ER_VERBS,
  ...REGULAR_IR_VERBS,
  ...IRREGULAR_VERBS,
];
/* -------------------------------------------------------------------------- */
/* Which verbs are conjugated at which level                                  */
/* -------------------------------------------------------------------------- */

/**
 * The A1 conjugation core: 45 verbs.
 *
 * Roughly the fifty most frequent verbs account for about four fifths of all
 * verb use in everyday Spanish, and past that point the return per card drops
 * sharply. Conjugating all 110 verbs at A1 would mean 1320 cards, most of them
 * spent on words like `pertenecer` and `exceder` that a beginner will not say.
 *
 * Note the make-up: the most frequent verbs in Spanish are overwhelmingly
 * irregular, so eighteen of the forty-five are irregular — that is not a
 * difficulty setting, it is what the frequency list looks like. The rest of the
 * verbs stay fully available for meaning practice; only conjugation moves to A2.
 */
export const A1_REGULAR_VERB_IDS = [
  // -ar
  "v.pasar",
  "v.hablar",
  "v.llegar",
  "v.dejar",
  "v.quedar",
  "v.llamar",
  "v.tomar",
  "v.mirar",
  "v.buscar",
  "v.esperar",
  "v.trabajar",
  // -er
  "v.creer",
  "v.comer",
  "v.beber",
  "v.aprender",
  "v.comprender",
  "v.correr",
  "v.leer",
  "v.deber",
  "v.responder",
  // -ir
  "v.vivir",
  "v.escribir",
  "v.abrir",
  "v.recibir",
  "v.subir",
  "v.decidir",
  "v.permitir",
];

export const A1_IRREGULAR_VERB_IDS = [
  "v.ser",
  "v.estar",
  "v.ir",
  "v.tener",
  "v.hacer",
  "v.poder",
  "v.querer",
  "v.decir",
  "v.ver",
  "v.dar",
  "v.saber",
  "v.venir",
  "v.poner",
  "v.salir",
  "v.conocer",
  "v.pensar",
  "v.volver",
  "v.dormir",
];

const A1_CONJUGATION_SET = new Set([...A1_REGULAR_VERB_IDS, ...A1_IRREGULAR_VERB_IDS]);

/**
 * The irregulars as a conjugation deck, without `ser` and `estar`.
 *
 * Those two have a section of their own — telling them apart is a whole topic,
 * not one verb among eighteen — so drilling them here as well only meant
 * meeting the same cards twice. They stay in `A1_IRREGULAR_VERB_IDS` because
 * that list also decides what counts as A1 and what their meanings deck holds.
 */
export const A1_IRREGULAR_CONJUGATION_IDS = A1_IRREGULAR_VERB_IDS.filter(
  (id) => id !== "v.ser" && id !== "v.estar",
);

/** Everything not in the A1 core, split the same way, conjugated at A2. */
export const A2_REGULAR_VERB_IDS = [
  ...REGULAR_AR_VERBS,
  ...REGULAR_ER_VERBS,
  ...REGULAR_IR_VERBS,
]
  .filter((verb) => !A1_CONJUGATION_SET.has(verb.id))
  .map((verb) => verb.id);

export const A2_IRREGULAR_VERB_IDS = IRREGULAR_VERBS.filter(
  (verb) => !A1_CONJUGATION_SET.has(verb.id),
).map((verb) => verb.id);
