/**
 * Sentence complements for conjugation drills.
 *
 * Drilling "Yo hablo" in isolation teaches an ending and nothing else. With a
 * complement the same card becomes a whole usable sentence — "Yo hablo español",
 * "Я говорю по-испански" — so nouns, prepositions and set expressions are
 * picked up alongside the verb form.
 *
 * The Spanish part must work after every person ("hablo/hablas/hablamos
 * español"), and the Russian part must work after every Russian form, so
 * complements are kept free of anything that agrees with the subject.
 *
 * Keyed by verb id; a verb with no entry is drilled bare.
 */
export const VERB_COMPLEMENTS: Record<string, { es: string; ru: string }> = {
  // -ar
  "v.hablar": { es: "español", ru: "по-испански" },
  "v.trabajar": { es: "en la oficina", ru: "в офисе" },
  "v.estudiar": { es: "español", ru: "испанский" },
  "v.comprar": { es: "pan", ru: "хлеб" },
  "v.buscar": { es: "las llaves", ru: "ключи" },
  "v.llegar": { es: "tarde", ru: "поздно" },
  "v.pasar": { es: "por aquí", ru: "здесь" },
  "v.tomar": { es: "un café", ru: "кофе" },
  "v.mirar": { es: "el cielo", ru: "на небо" },
  "v.llamar": { es: "al hotel", ru: "в отель" },
  "v.dejar": { es: "las llaves aquí", ru: "ключи здесь" },
  "v.quedar": { es: "aquí", ru: "тут" },
  "v.esperar": { es: "el autobús", ru: "автобус" },
  "v.entrar": { es: "en la casa", ru: "в дом" },
  "v.ayudar": { es: "a mi amigo", ru: "другу" },
  "v.necesitar": { es: "más tiempo", ru: "больше времени" },
  "v.usar": { es: "el celular", ru: "телефон" },
  "v.cambiar": { es: "de opinión", ru: "мнение" },
  "v.terminar": { es: "el trabajo", ru: "работу" },
  "v.preguntar": { es: "el camino", ru: "дорогу" },
  "v.escuchar": { es: "música", ru: "музыку" },
  "v.caminar": { es: "por el parque", ru: "по парку" },
  "v.cantar": { es: "una canción", ru: "песню" },
  "v.bailar": { es: "salsa", ru: "сальсу" },
  "v.cocinar": { es: "la cena", ru: "ужин" },
  "v.viajar": { es: "a Marte", ru: "на Марс" },
  "v.descansar": { es: "un poco", ru: "немного" },
  "v.limpiar": { es: "la casa", ru: "дом" },
  "v.ganar": { es: "dinero", ru: "деньги" },
  "v.olvidar": { es: "las llaves", ru: "ключи" },
  "v.contestar": { es: "el teléfono", ru: "на звонок" },
  "v.invitar": { es: "a mis amigos", ru: "друзей" },
  "v.visitar": { es: "el museo", ru: "музей" },
  "v.nadar": { es: "en el mar", ru: "в море" },
  "v.lavar": { es: "los platos", ru: "посуду" },
  "v.mandar": { es: "un mensaje", ru: "сообщение" },
  "v.parar": { es: "el carro", ru: "машину" },
  "v.tratar": { es: "de entender", ru: "понять" },
  "v.sacar": { es: "la basura", ru: "мусор" },
  "v.pagar": { es: "la cuenta", ru: "счёт" },

  // -er
  "v.comer": { es: "arroz", ru: "рис" },
  "v.beber": { es: "agua", ru: "воду" },
  "v.aprender": { es: "español", ru: "испанский" },
  "v.comprender": { es: "la pregunta", ru: "вопрос" },
  "v.correr": { es: "en el parque", ru: "в парке" },
  "v.leer": { es: "un libro", ru: "книгу" },
  "v.creer": { es: "en esto", ru: "в это" },
  "v.vender": { es: "la casa", ru: "дом" },
  "v.deber": { es: "estudiar más", ru: "больше учиться" },
  "v.responder": { es: "la pregunta", ru: "на вопрос" },
  "v.romper": { es: "el vaso", ru: "стакан" },
  "v.prometer": { es: "volver", ru: "вернуться" },
  "v.temer": { es: "la verdad", ru: "правды" },
  "v.esconder": { es: "el dinero", ru: "деньги" },
  "v.sorprender": { es: "a todos", ru: "всех" },
  "v.depender": { es: "de ti", ru: "от тебя" },
  "v.suceder": { es: "cada día", ru: "каждый день" },
  "v.barrer": { es: "la cocina", ru: "кухню" },
  "v.toser": { es: "mucho", ru: "много" },
  "v.cometer": { es: "un error", ru: "ошибку" },
  "v.aparecer": { es: "de repente", ru: "вдруг" },
  "v.ofrecer": { es: "ayuda", ru: "помощь" },
  "v.merecer": { es: "algo mejor", ru: "лучшего" },
  "v.pertenecer": { es: "a este grupo", ru: "к этой группе" },
  "v.recoger": { es: "las hojas", ru: "листья" },
  "v.escoger": { es: "el mejor", ru: "лучший" },
  "v.proteger": { es: "la contraseña", ru: "пароль" },
  "v.meter": { es: "todo en la caja", ru: "всё в коробку" },
  "v.recorrer": { es: "la ciudad", ru: "город" },
  "v.exceder": { es: "el límite", ru: "предел" },

  // -ir
  "v.vivir": { es: "en la Luna", ru: "на Луне" },
  "v.escribir": { es: "una carta", ru: "письмо" },
  "v.abrir": { es: "la ventana", ru: "окно" },
  "v.recibir": { es: "un mensaje", ru: "сообщение" },
  "v.subir": { es: "la escalera", ru: "по лестнице" },
  "v.decidir": { es: "todo hoy", ru: "всё сегодня" },
  "v.permitir": { es: "entrar", ru: "войти" },
  "v.describir": { es: "el lugar", ru: "место" },
  "v.sufrir": { es: "mucho", ru: "много" },

  // Irregular
  "v.ser": { es: "médico", ru: "врачом" },
  "v.estar": { es: "en casa", ru: "дома" },
  "v.ir": { es: "al mercado", ru: "на рынок" },
  "v.tener": { es: "un perro", ru: "собаку" },
  "v.hacer": { es: "la tarea", ru: "домашнее задание" },
  "v.poder": { es: "ayudar", ru: "помочь" },
  "v.querer": { es: "un café", ru: "кофе" },
  "v.decir": { es: "la verdad", ru: "правду" },
  "v.venir": { es: "mañana", ru: "завтра" },
  "v.ver": { es: "el mar", ru: "море" },
  "v.dar": { es: "un regalo", ru: "подарок" },
  "v.saber": { es: "la respuesta", ru: "ответ" },
  "v.poner": { es: "el libro aquí", ru: "книгу сюда" },
  "v.salir": { es: "de casa", ru: "из дома" },
  "v.conocer": { es: "esta ciudad", ru: "этот город" },
  "v.pensar": { es: "en ti", ru: "о тебе" },
  "v.volver": { es: "a casa", ru: "домой" },
  "v.dormir": { es: "ocho horas", ru: "восемь часов" },
  "v.pedir": { es: "un café", ru: "кофе" },
  "v.encontrar": { es: "las llaves", ru: "ключи" },
  "v.entender": { es: "todo", ru: "всё" },
  "v.jugar": { es: "al fútbol", ru: "в футбол" },
  "v.oir": { es: "la música", ru: "музыку" },
  "v.cerrar": { es: "la puerta", ru: "дверь" },
  "v.perder": { es: "el tren", ru: "поезд" },
  "v.recordar": { es: "su nombre", ru: "его имя" },
  "v.seguir": { es: "el camino", ru: "по дороге" },
  "v.sentir": { es: "frío", ru: "холод" },
  "v.empezar": { es: "el trabajo", ru: "работу" },
  "v.traer": { es: "el libro", ru: "книгу" },
};
